/*
	Clean the survey data sets and and save as separate Stata-dta-files
	and append into one survey data file.
	This file cleans 2006 survey.
NOTE THAT THIS FILE IS NOT RELEVANT FOR THIS PROJECT.
*/

clear
capture log close
version 13
set more off
set mem 4g
* Header do-File with path definitions, those end up in global macros.
include project_paths
log using `"${PATH_OUT_DATA}/log/`1'.log"', replace

*********************************
* Load Stata file generated by readin-file.
use `"${PATH_OUT_DATA}/surveydataraw2006.dta"', clear


rename quest id

/* Not asked in 2006
- hometype
- socialhome
*/


gen age=.
replace age=p2
label var age "age or respondent"
*check
sum age

gen agecat=1 if age<=24
replace agecat=2 if age>24 & age<=34
replace agecat=3 if age>34 & age<=44
replace agecat=4 if age>44 & age<=54
replace agecat=5 if age>54 & age<=64
replace agecat=6 if age>64
label var agecat "age category of respondent"
label define agecatl 1 "18-24" 2 "25-34" 3 "35-44" 4 "45-54" 5 "55-64" 6 "65+"
label values agecat agecatl
*check  
tab agecat

gen ownership=.
replace ownership=1 if p6=="Eigenaar"
replace ownership=2 if p6=="Huurder"
label var ownership "home ownership"
label define ownershipl 1 "owner" 2 "tenant"
label values ownership ownershipl
*check 
tab ownership
tab p6


gen income=.
replace income=1 if p8=="Minder dan � 600 : Minder dan +/- 24.000 BEF"
replace income=	2 if p8=="Tussen � 600 en � 999,99 : Tussen +/-24.000 en +/-40.000 BEF"
replace income=3 if p8=="Tussen � 1.000 en � 1.499,99 : Tussen +/-40.000 en +/-60.000"
replace income=4 if p8=="Tussen � 1.500 en � 1.999,99 : Tussen +/-60.000 en +/-80.000"
replace income=5 if p8=="Tussen � 2.000 en � 2.499,99 : Tussen +/-80.000 en +/-100.00"
replace income=6 if p8=="Tussen � 2.500 en � 3.749,99 : Tussen +/-100.000 en +/-150.0"
replace income=7 if p8=="Tussen � 3.750 en � 4.999,99 : Tussen +/-150.000 en +/-200.0"
replace income=8 if p8=="Tussen � 5.000 en � 6.249,99 : Tussen +/-200.000 en +/-250.0"
replace income=9 if p8=="Meer dan � 6.250 : Meer dan +/-250.000 BEF"
replace income=10 if p8=="Ik zeg dit liever niet"
label var income "family net income"
#delimit ;
label define incomel 1 "< EUR 600" 2 "EUR 600-999.99" 3 "EUR 1,000-1,499.99"
	4 "EUR 1,500-1,999.99 " 5 "EUR 2,000-2,499.99" 6 "EUR 2,500-3,749.99"
	7 "EUR 3,750-4,999.99" 8 "EUR  5,000-6,249.99" 9 "> EUR 6,250"
	10 "I prefer not to tell"
;
#delimit cr
label values income incomel
*check
tab p8
tab income	

rename p1a size_hh
label var size_hh "size of household"
*check
tab size_hh
//Two did not want to give an indication of size. Code it as missing
replace size_hh=. if size_hh==99

rename p1b kids
label var kids "number of kids in household <14 years"
*check
tab kids

gen gender=.
replace gender=1 if p3=="Man"
replace gender=2 if p3=="Vrouw"
label var gender "gender of respondent"
label define genderl 1 "male" 2 "female"
label values gender genderl
*check
tab gender
tab p3

gen education=.
replace education=1 if p4=="Lager onderwijs"
replace education=2 if p4=="Lager secundair onderwijs" | p4=="Hoger secundair onderwijs"
replace education=3 if p4=="Hoger onderwijs korte type (bv. graduaat, A1-diploma,�)" |  p4=="Niet-universitair hoger onderwijs lange type" //diff
replace education=4 if p4=="Universitair onderwijs"
#delimit ;
label define educationl 1 "primary education" 2 "secondary education" 
	3 "higher eudcation (non-uni)" 4 "university"
;
#delimit cr
label values education educationl
*check
tab p4
tab education

gen employment=.
replace employment=1 if p5=="Voltijds werkend"
replace employment=1 if p5=="Deeltijds werkend"
replace employment=3 if p5=="Huisvrouw of huisman"
replace employment=4 if p5=="Werkloos of werkonbekwaam (bv. omwille van ziekte)"
replace employment=5 if p5=="Bruggepensioneerd of gepensioneerd"
label var employment "employment status(more details available)"
#delimit ;
label define employmentl 1 "working" 2 "student" 3 "housewife" 
	4 "unemployed and other inactive" 5 "retired" 6 "don't know"
;
#delimit cr
label values employment employmentl
*check
tab p5
tab employment

//NOTE: in 2006, this was only asked to people NOT on default
//I have adapted by using info on default supplier in variabel LEVEL
gen supplier=.
replace supplier=9 if lw6ab=="EBEM"
replace supplier=10 if lw6ab=="Ecopower"
replace supplier=12 if lw6ab=="Electrabel Customer Solutions"
replace supplier=20 if lw6ab=="Essent Belgium"
replace supplier=25 if lw6ab=="Luminus" //only called luminus
replace supplier=27 if lw6ab=="Nuon Belgium"
replace supplier=34 if lw6ab=="Wase Wind"
replace supplier=98 if lw6ab=="Andere, namelijk ..."
replace supplier=99 if lw6ab=="Weet niet"
replace supplier=95 if lw6ab=="City Power" //apparently part of luminus since 2004
label var supplier "current electricity supplier"
#delimit ;
label define supplierl 1 "antargaz" 2 "belpower" 6 "eon" 9 "ebem" 10 "ecopower" 
	12 "ecs" 14 "elegant" 	17 "eneco" 20 "essent" 24 "lampiris" 25 "edf-luminus" 
	27 "nuon" 28 "octaplus" 32 "spe-luminus" 34 "wasewind"	35 "wingas"	43 "energie2030"
	45 "eni" 49 "watz" 50 "agem TSO" 51 "eandis TSO" 52 "infrax TSO" 53 "pbe TSO"
	54 "social supplier" 95 "citypower" 96 "interelecta" 97 "iverlek" 98 "other" 
	99 "don't know"
;
#delimit cr
label values supplier supplierl
*check 
tab lw6ab
tab supplier

//NOW add the defaults so that we have a value for supplier for every observation
gen help=.
replace help=1 if level=="Luminus"
replace help=2 if level=="Electrabel Customer Solutions"
label var help "default supplier in the muni of observation"
label defin helpl 1 "luminus" 2 "electrabel"
label values help helpl
*check
tab level
tab help

replace supplier=12 if supplier==. & help==2 //334
replace supplier=25 if supplier==. & help==1 //102
*check supplier
tab supplier


gen contract=.
replace contract=1 if lw6aa=="Ja, reeds een contract aangegaan"
replace contract=2 if lw6aa=="Neen, geen contract aangegaan"
replace contract=3 if lw6aa=="Weet niet"
label var contract "have you signed a contract? (in 2011-13 only asked if potentially on a default)"
label define contractl 1 "yes (i.e. on a competitive trariff)" 2 "no (i.e. on default or social tariff)" 3 "don't know"
label values contract contractl
*check
tab lw6aa
tab contract
tab supplier contract

gen socialtariff=.
replace socialtariff=2 
replace socialtariff=1 if supplier==50 | supplier==51 | supplier==52 | supplier==53 | supplier==54 | supplier==97 
label var socialtariff "on a social tariff (not an original question)"
label define socialtariffl 1 "yes" 2 "no"
label values socialtariff socialtariffl
*check
tab socialtariff


gen default=.
replace default=1
replace default=2 if contract==1
replace default=3 if contract==3
label var default "on a default tariff (not an original question)"
label define defaultl 1 "yes" 2 "no" 3 "don't know"
label values default defaultl
*check
tab contract
tab default
//1544
tab supplier default


//In 2006, Q: With how many suppliers did you have a contract since the liberalisation
//NOTE: In other years the question was: how often have you switched = 
//		--> one supplier less than coded
// potentially problematic if someone has signed a contract with ANOTHER than default supplier
//		in the beginning (this could in principle be 1 (but unlikely), here it is coded as a 0)
gen sw_frequency=.
replace sw_frequency=98 if lw6ac=="Weet niet" | lw6ac=="Andere"
replace sw_frequency=0 if lw6ac=="E�n leverancier"
replace sw_frequency=1 if lw6ac=="Twee leveranciers"
replace sw_frequency=2 if lw6ac=="Drie leveranciers"
replace sw_frequency=3 if lw6ac=="Vier leveranciers"
label var sw_frequency "how often have you changed elec supplier"
label define sw_frequencyl 98 "don't know" 
label values sw_frequency sw_frequencyl
*check
tab lw6ac
tab sw_frequency
tab default if sw_frequency==.
tab default sw_frequency


//NOTE: In 2006, this is constructed from question 6ac
//In >2011 this variable has missing values if person is on default
// ->same here
gen sw_history=. //all those that did not answer sw_frequency are on default
				 // tab contract if sw_frequency==.
replace sw_history=1 if sw_frequency==1 | sw_frequency==2 | sw_frequency==3 | sw_frequency==4
replace sw_history=2 if sw_frequency==0
replace sw_history=3 if sw_frequency==98
label var sw_history "have you ever changed electricity supplier"
label define sw_historyl 1 "yes" 2 "no" 3 "don't know"
label values sw_history sw_historyl
*check
tab sw_history

gen no_sw_possibility=.
replace no_sw_possibility=1 if lw20a=="Eerder van toepassing" | lw20a=="Helemaal van toepassing"
replace no_sw_possibility=0 if lw20a=="Helemaal NIET van toepassing" | lw20a=="NIET echt van toepassing" | lw20a=="Weet niet (INT: niet voorlezen)"
label var no_sw_possibility "Haven't switched supplier bec didn't know that I can switch"
label define no_sw_possibilityl 0 "Not true" 1 "True"
label values no_sw_possibility no_sw_possibilityl
*check
tab lw20a
tab no_sw_possibility

gen no_sw_cheaper=.
replace no_sw_cheaper=1 if lw20b=="Eerder van toepassing" | lw20b=="Helemaal van toepassing"
replace no_sw_cheaper=0 if lw20b=="Helemaal NIET van toepassing" | lw20b=="NIET echt van toepassing" | lw20b=="Weet niet (INT: niet voorlezen)"
label var no_sw_cheaper "Haven't switched supplier bec didn't receive a better offer"
label define no_sw_cheaperl 0 "Not true" 1 "True"
label values no_sw_cheaper no_sw_cheaperl
*check
tab lw20b	
tab no_sw_cheaper	

gen no_sw_comparison=.
replace no_sw_comparison=1 if lw20c=="Eerder van toepassing" | lw20c=="Helemaal van toepassing"
replace no_sw_comparison=0 if lw20c=="Helemaal NIET van toepassing" | lw20c=="NIET echt van toepassing" | lw20c=="Weet niet (INT: niet voorlezen)"
label var no_sw_comparison "Haven't switched supplier bec difficult to compare suppliers"
label define no_sw_comparisonl 0 "Not true" 1 "True"
label values no_sw_comparison no_sw_comparisonl
*check
tab lw20c
tab no_sw_comparison


gen no_sw_feelgood=.
replace no_sw_feelgood=1 if lw20d=="Eerder van toepassing" | lw20d=="Helemaal van toepassing"
replace no_sw_feelgood=0 if lw20d=="Helemaal NIET van toepassing" | lw20d=="NIET echt van toepassing" | lw20d=="Weet niet (INT: niet voorlezen)"
label var no_sw_feelgood "Haven't switched supplier bec feel well with current supplier"
label define no_sw_feelgoodl 0 "Not true" 1 "True"
label values no_sw_feelgood no_sw_feelgoodl
*check
tab lw20d
tab no_sw_feelgood


gen no_sw_interest=.
replace no_sw_interest=1 if lw20e=="Eerder van toepassing" | lw20e=="Helemaal van toepassing"
replace no_sw_interest=0 if lw20e=="Helemaal NIET van toepassing" | lw20e=="NIET echt van toepassing" | lw20e=="Weet niet (INT: niet voorlezen)"
label var no_sw_interest "Haven't switched supplier bec not interested in a switch"
label define no_sw_interestl 0 "Not true" 1 "True"
label values no_sw_interest no_sw_interestl
*check
tab lw20e
tab no_sw_interest


gen no_sw_wrong=.
replace no_sw_wrong=1 if lw20f=="Eerder van toepassing" | lw20f=="Helemaal van toepassing"
replace no_sw_wrong=0 if lw20f=="Helemaal NIET van toepassing" | lw20f=="NIET echt van toepassing" | lw20f=="Weet niet (INT: niet voorlezen)"
label var no_sw_wrong "Haven't switched supplier bec too many things could go wrong"
label define no_sw_wrongl 0 "Not true" 1 "True"
label values no_sw_wrong no_sw_wrongl
*check
tab lw20f
tab no_sw_wrong


//consumption
gen cons_day =ei7ad
replace cons_day="" if ei7ad=="Weet niet" | ei7ad=="9999999" | ei7ad=="999999999"
destring cons_day, replace
*tab cons_day

gen cons_night =ei7ae
replace cons_night="" if ei7ae=="Weet niet" 
replace cons_night="1057" if ei7ae=="1057999999" 
replace cons_night="505" if ei7ae=="5059999999"
destring cons_night, replace

gen cons_peak =ei7af
replace cons_peak="" if ei7af=="Weet niet" 
destring cons_peak, replace

*SUM
replace cons_day=0 if cons_day==.
replace cons_night=0 if cons_night==.
replace cons_peak=0 if cons_peak==.
gen consumption_help=cons_day + cons_night + cons_peak

gen consumption=.
replace consumption=1 if consumption_help<900
replace consumption=2 if consumption_help>=900 & consumption_help<2350
replace consumption=3 if consumption_help>=2350 & consumption_help<5500
replace consumption=4 if consumption_help>=5500 & consumption_help<13750
replace consumption=5 if consumption_help>=13750
replace consumption=6 if ei7ad=="Weet niet" | ei7ad=="9999999" | ei7ad=="999999999"
label var consumption "yearly electricity consumption (past year)"
#delimit;
label define consumptionl 1 "<900kWh" 2 "900-2350 kWh" 3 "2350-5500 kWh" 4 "5500-13750 kWh"
	5 ">13750 kWh" 6 "don't know"
;
#delimit cr
label values consumption consumptionl
*check 
tab consumption 
drop consumption_help

gen energycost=.
label var energycost "How important are energy costs within total HH costs"
replace energycost=1 if ei8=="Helemaal niet belangrijk"
replace energycost=2 if ei8=="Niet echt zo belangrijk"
replace energycost=3 if ei8=="Nogal belangrijk"
replace energycost=4 if ei8=="Zeer belangrijk"
replace energycost=5 if ei8=="Geen mening  (INT: niet voorlezen)"
label define energycostl 1 "not important at all" 2 "rather not important" 3 "rather important" 4 "very important" 5 "no opinion"
label values energycost energycostl
*check
tab energycost

gen green_contract=.
replace green_contract=1 if ge3=="Ja"
replace green_contract=2 if ge3=="Nee"
replace green_contract=3 if ge3=="Weet niet"
label var green_contract "current contract is green (only 50% asked)"
label define green_contractl 1 "yes" 2 "no" 3 "don't know"
label values green_contract green_contractl
*check
tab green_contract
tab green_contract contract


/* two modalities were not asked: 
- sw_solar
- sw_nuclear */

gen sw_cheaper=.
replace sw_cheaper=1 if lw9aa=="Eerder van toepassing" | lw9aa=="Helemaal van toepassing"
replace sw_cheaper=2 if lw9aa=="NIET echt van toepassing"  | lw9aa=="Helemaal NIET van toepassing"
replace sw_cheaper=3 if lw9aa=="Weet niet (INT: niet voorlezen)"
label var sw_cheaper "supplier chosen because cheaper (only if elec contract was signed)"
label define sw_cheaperl  1 "yes" 2 "no" 3 "don't know"
label values sw_cheaper sw_cheaperl
*check
tab sw_cheaper
tab lw9aa

gen sw_service=.
replace sw_service=1 if lw9ab=="Eerder van toepassing" | lw9ab=="Helemaal van toepassing"
replace sw_service=2 if lw9ab=="NIET echt van toepassing"  | lw9ab=="Helemaal NIET van toepassing"
replace sw_service=3 if lw9ab=="Weet niet (INT: niet voorlezen)"
label var sw_service "Have chosen supplier because better service (only if elec contract was signed)"
label define sw_servicel 1 "yes" 2 "no" 3 "don't know"	
label values sw_service sw_servicel
*check
tab sw_service
tab lw9ab

gen sw_reliable=.
replace sw_reliable=1 if lw9ac=="Eerder van toepassing" | lw9ac=="Helemaal van toepassing"
replace sw_reliable=2 if lw9ac=="NIET echt van toepassing"  | lw9ac=="Helemaal NIET van toepassing"
replace sw_reliable=3 if lw9ac=="Weet niet (INT: niet voorlezen)"
label var sw_reliable "Have chosen supplier because reliable (only if elec contract was signed)"
label define sw_reliablel 1 "yes" 2 "no" 3 "don't know"	
label values sw_reliable sw_reliablel
*check
tab sw_reliable
tab lw9ac

gen sw_family=.
replace sw_family=1 if lw9ad=="Eerder van toepassing" | lw9ad=="Helemaal van toepassing"
replace sw_family=2 if lw9ad=="NIET echt van toepassing"  | lw9ad=="Helemaal NIET van toepassing"
replace sw_family=3 if lw9ad=="Weet niet (INT: niet voorlezen)"
label var sw_family "Have chosen supplier because same as family/acquaintances (only if elec contract was signed)"
label define sw_familyl 1 "yes" 2 "no" 3 "don't know"
label values sw_family sw_familyl
*check
tab sw_family
tab lw9ad

gen sw_green=.
replace sw_green=1 if lw9ag=="Eerder van toepassing" | lw9ag=="Helemaal van toepassing"
replace sw_green=2 if lw9ag=="NIET echt van toepassing"  | lw9ag=="Helemaal NIET van toepassing"
replace sw_green=3 if lw9ag=="Weet niet (INT: niet voorlezen)"
label var sw_green "Have chosen supplier because green elec (only if elec contract was signed)"
label define sw_greenl 1 "yes" 2 "no" 3 "don't know"
label values sw_green sw_greenl
*check
tab sw_green
tab lw9ag

gen sw_additional=.
replace sw_additional=1 if lw9ah=="Eerder van toepassing" | lw9ah=="Helemaal van toepassing"
replace sw_additional=2 if lw9ah=="NIET echt van toepassing"  | lw9ah=="Helemaal NIET van toepassing"
replace sw_additional=3 if lw9ah=="Weet niet (INT: niet voorlezen)"
label var sw_additional "Have chosen supplier because additional service (only if elec contract was signed)"
label define sw_additionall 1 "yes" 2 "no" 3 "don't know"
label values sw_additional sw_additionall
*check
tab sw_additional
tab lw9ah


* Create year variable (to facilitate merging of yearly surveys).
gen year=2006

* Rename weight variable.
rename weight0 weight

***
#delimit;
keep weight id //hometype socialhome 
	ownership income size_hh kids gender education employment
	supplier contract sw_history sw_frequency //same_supplier green_contract 
	//sw_reason_gen same_reason 
	sw_cheaper sw_service sw_reliable //sw_solar sw_nuclear 
	sw_family sw_green sw_additional no_sw_possibility //no_sw_how 
	no_sw_cheaper no_sw_comparison //no_sw_effort 
	no_sw_feelgood no_sw_interest no_sw_wrong //no_sw_none no_sw_dontknow 
	//green_confidence green_future green_reason heating1 heating2 heating3 meter 
	consumption 
	energycost //solar price_change price_percent aware_free info_liberalization 
	//aware_vreg aware_vtest same_aware sw_intention sw_intention_default sw_saving 
	//sw_saving_nb 
	socialtariff default
	age agecat
;
#delimit cr
numlabel , add


* Create a year variable to identify surveys when appending them into one file.
gen year = 2006

*********************************
* Save cleaned 2006 survey as Stata file.
save `"${PATH_OUT_DATA}/surveydata2006_clean"', replace
****************************************************************************
