/*
	Clean the survey data sets and and save as separate Stata-dta-files
	and append into one survey data file.
	This file cleans 2009 survey.
NOTE THAT THIS FILE IS NOT RELEVANT FOR THIS PROJECT.
*/

clear
capture log close
version 13
set more off
set mem 4g
* Header do-File with path definitions, those end up in global macros.
include project_paths
log using `"${PATH_OUT_DATA}/log/`1'.log"', replace

*********************************
* Load Stata file generated by readin-file.
use `"${PATH_OUT_DATA}/surveydataraw2009.dta"', clear

rename Respondent_ID id
destring id, replace

/* not asked in 2009
- socialhome
*/

gen age=.
replace age=P4
label var age "age or respondent"
*check
sum age

gen agecat=1 if age<=24
replace agecat=2 if age>24 & age<=34
replace agecat=3 if age>34 & age<=44
replace agecat=4 if age>44 & age<=54
replace agecat=5 if age>54 & age<=64
replace agecat=6 if age>64
label var agecat "age category of respondent"
label define agecatl 1 "18-24" 2 "25-34" 3 "35-44" 4 "45-54" 5 "55-64" 6 "65+"
label values agecat agecatl
*check  
tab agecat
tab cP4

// NOTE add 0 because of year 2004
gen hometype=.
replace hometype=1 if P8A=="huis"
replace hometype=2 if P8A=="appartement"
label var hometype "type of house"
label define hometypel 0 "other" 1 "house" 2 "apartment" 
label values hometype hometypel  
*check
tab P8A
tab hometype



gen ownership=.
replace ownership=1 if P8B=="eigenaar"
replace ownership=2 if P8B=="huurder"
label var ownership "home ownership"
label define ownershipl 1 "owner" 2 "tenant"
label values ownership ownershipl
*check 
tab P8B
tab ownership


gen income=.
replace income=1 if P11=="Minder dan � 600"
replace income=2 if P11=="Tussen � 600 en � 999,99"
replace income=3 if P11=="Tussen � 1.000 en � 1.499,99"
replace income=4 if P11=="Tussen � 1.500 en � 1.999,99"
replace income=5 if P11=="Tussen � 2.000 en � 2.499,99"
replace income=6 if P11=="Tussen � 2.500 en � 3.749,99"
replace income=7 if P11=="Tussen � 3.750 en � 4.999,99"
replace income=8 if P11=="Tussen � 5.000 en � 6.249,99"
replace income=9 if P11=="Meer dan � 6.250"
replace income=10 if P11=="Ik zeg dit liever niet"
label var income "family net income"
#delimit ;
label define incomel 1 "< EUR 600" 2 "EUR 600-999.99" 3 "EUR 1,000-1,499.99"
	4 "EUR 1,500-1,999.99 " 5 "EUR 2,000-2,499.99" 6 "EUR 2,500-3,749.99"
	7 "EUR 3,750-4,999.99" 8 "EUR  5,000-6,249.99" 9 "> EUR 6,250"
	10 "I prefer not to tell"
;
#delimit cr
label values income incomel
*check
tab P11
tab income	


rename P2 size_hh
label var size_hh "size of household"
*check
tab size_hh


rename P3 kids
label var kids "number of kids in household <14 years"
*check
tab kids

gen gender=.
replace gender=1 if P5=="Man"
replace gender=2 if P5=="Vrouw"
label var gender "gender of respondent"
label define genderl 1 "male" 2 "female"
label values gender genderl
*check
tab P5
tab gender


gen education=.
replace education=1 if P6=="Lager onderwijs"
replace education=2 if P6=="Lager secundair onderwijs" | P6=="Hoger secundair onderwijs"
replace education=3 if P6=="Hoger onderwijs korte type (bv. graduaat, A1-diploma,...)" | P6=="Niet-universitair hoger onderwijs lange type" //diff
replace education=4 if P6=="Universitair onderwijs"
#delimit ;
label define educationl 1 "primary education" 2 "secondary education" 
	3 "higher eudcation (non-uni)" 4 "university"
;
#delimit cr
label values education educationl
*check
tab education
tab P6


gen employment=.
replace employment=1 if P7=="Deeltijds werkend" | P7=="Voltijds werkend"
replace employment=3 if P7=="Huisvrouw of huisman"
replace employment=4 if P7=="Werkloos of werkonbekwaam (bv. omwille van ziekte)"
replace employment=5 if P7=="Bruggepensioneerd of gepensioneerd"
label var employment "employment status (more details available)"
#delimit ;
label define employmentl 1 "working" 2 "student" 3 "housewife" 
	4 "unemployed and other inactive" 5 "retired" 6 "don't know"
;
#delimit cr
label values employment employmentl
*check
tab P7
tab employment

gen supplier=.
replace supplier=9 if LW6=="EBEM (Elektriciteitsbedrijf Merksplas)"
replace supplier=10 if LW6=="Ecopower"
replace supplier=12 if LW6=="Electrabel Customer Solutions"
replace supplier=17 if LW6=="Eneco Energie Levering"
replace supplier=20 if LW6=="Essent Belgium"
replace supplier=24 if LW6=="Lampiris"
replace supplier=25 if LW6=="Luminus"
replace supplier=27 if LW6=="Nuon Belgium"
*replace supplier=2 if LW6=="Reibel � Belpower"
replace supplier=32 if LW6=="SPE"
replace supplier=34 if LW6=="Wase Wind"
replace supplier=51 if LW6=="Eandis" // (nvdr: netbeheerder = sociale leverancier)
replace supplier=52 if LW6=="Infrax" // (nvdr: netbeheerder = sociale leverancier)
replace supplier=53 if LW6=="PBE" // (nvdr: netbeheerder= sociale leverancier)
replace supplier=50 if LW6=="AGEM" //(nvdr: netbeheerder= sociale leverancier)
replace supplier=52 if LW6=="Sociale leverancier"
replace supplier=98 if LW6=="Andere, namelijk ..."
replace supplier=99 if LW6=="Weet niet"
label var supplier "current electricity supplier"
#delimit ;
label define supplierl 1 "antargaz" 2 "belpower" 6 "eon" 9 "ebem" 10 "ecopower" 
	12 "ecs" 14 "elegant" 	17 "eneco" 20 "essent" 24 "lampiris" 25 "edf-luminus" 
	27 "nuon" 28 "octaplus" 32 "spe-luminus" 34 "wasewind"	35 "wingas"	43 "energie2030"
	45 "eni" 49 "watz" 50 "agem TSO" 51 "eandis TSO" 52 "infrax TSO" 53 "pbe TSO"
	54 "social supplier" 95 "citypower" 96 "interelecta" 97 "iverlek" 98 "other" 
	99 "don't know"
;
#delimit cr
label values supplier supplierl
*check 
tab LW6
tab supplier



gen contract=.
replace contract=1 if LW5=="Ja, contract aangegaan"
replace contract=2 if LW5=="Neen, geen contract aangegaan"
replace contract=3 if LW5=="Weet niet"
label var contract "have you signed a contract? (in 2011-13 only asked if potentially on a default)"
label define contractl 1 "yes (i.e. on a competitive trariff)" 2 "no (i.e. on default or social tariff)" 3 "don't know"
label values contract contractl
*check
tab LW5
tab contract

tab supplier contract


gen socialtariff=.
replace socialtariff=2 
replace socialtariff=1 if supplier==50 | supplier==51 | supplier==52 | supplier==53 | supplier==54 | supplier==97 
label var socialtariff "on a social tariff with elec (not an original question)"
label define socialtariffl 1 "yes" 2 "no"
label values socialtariff socialtariffl
*check
tab socialtariff


gen default=.
replace default=2
replace default=1 if contract==2
replace default=3 if contract==3
label var default "on a default tariff (not an original question)"
label define defaultl 1 "yes" 2 "no" 3 "don't know"
label values default defaultl
*check
tab contract
tab default

tab supplier default


//In 2009, Q: With how many electricity suppliers did you sign a contract
//			  since the elec market liberalisation (incl your current supplier)
//NOTE: In other years the question was: how often have you switched = 
//		--> one supplier less than coded
// problematic if someone has signed a contract with ANOTHER than default supplier
//		in the beginning (should be a 1 but is coded as a 0 here)
rename LW7 sw_frequency
destring sw_frequency, replace
replace sw_frequency=sw_frequency-1
label var sw_frequency "how often have you changed elec supplier"
label define sw_frequencyl 98 "don't know" 
label values sw_frequency sw_frequencyl
*check
tab sw_frequency

//NOTE: In 2009 this is constructed from question 7 
//In >2011 this variable has missing values if person is on default
// ->same here
gen sw_history=. //all those that did not answer sw_frequency are on default
				 // tab contract if sw_frequency==.
replace sw_history=1 if sw_frequency==1 | sw_frequency==2 | sw_frequency==3 | sw_frequency==4
replace sw_history=2 if sw_frequency==0
replace sw_history=3 if sw_frequency==98
label var sw_history "have you ever changed electricity supplier"
label define sw_historyl 1 "yes" 2 "no" 3 "don't know"
label values sw_history sw_historyl
*check
tab sw_history

gen no_sw_possibility=.
replace no_sw_possibility=0 if LW23_W201=="No"
replace no_sw_possibility=1 if LW23_W201=="Yes"
label var no_sw_possibility "Haven't switched supplier bec didn't know that I can switch"
label define no_sw_possibilityl 0 "Not true" 1 "True"
label value no_sw_possibility no_sw_possibilityl
*check
tab LW23_W201
tab no_sw_possibility


//now put missing values if they have not been asekd this questions
#delimit ;
replace no_sw_possibility=. if LW23_W201=="No" & LW23_W202=="No" & LW23_W203=="No" & 
	LW23_W204=="No" & LW23_W205=="No" & LW23_W206=="No" & LW23_W207=="No" & 
	LW23_W208=="No" & LW23_W209=="No"
;
#delimit cr
tab no_sw_possibility


gen no_sw_how=.
replace no_sw_how=0 if LW23_W202=="No"
replace no_sw_how=1 if LW23_W202=="Yes"
label var no_sw_how "Haven't switched supplier bec didn't know HOW to switch"
label define no_sw_howl 0 "Not true" 1 "True"
label value no_sw_how no_sw_howl
*check
tab LW23_W202
tab no_sw_how


//now put missing values if they have not been asekd this questions
#delimit ;
replace no_sw_how=. if LW23_W201=="No" & LW23_W202=="No" & LW23_W203=="No" & 
	LW23_W204=="No" & LW23_W205=="No" & LW23_W206=="No" & LW23_W207=="No" & 
	LW23_W208=="No" & LW23_W209=="No"
;
#delimit cr
tab no_sw_how


gen no_sw_cheaper=.
replace no_sw_cheaper=0 if LW23_W203=="No"
replace no_sw_cheaper=1 if LW23_W203=="Yes"
label var no_sw_cheaper "Haven't switched supplier bec didn't receive a better offer"
label define no_sw_cheaperl 0 "Not true" 1 "True"
label value no_sw_cheaper no_sw_cheaperl
*check
tab LW23_W203
tab no_sw_cheaper


//now put missing values if they have not been asekd this questions
#delimit ;
replace no_sw_cheaper=. if LW23_W201=="No" & LW23_W202=="No" & LW23_W203=="No" & 
	LW23_W204=="No" & LW23_W205=="No" & LW23_W206=="No" & LW23_W207=="No" & 
	LW23_W208=="No" & LW23_W209=="No"
;
#delimit cr
tab no_sw_cheaper
gen no_sw_comparison=.
replace no_sw_comparison=0 if LW23_W204=="No"
replace no_sw_comparison=1 if LW23_W204=="Yes"
label var no_sw_comparison "Haven't switched supplier bec difficult to compare suppliers"
label define no_sw_comparisonl 0 "Not true" 1 "True"
label value no_sw_comparison no_sw_comparisonl
*check
tab LW23_W204
tab no_sw_comparison


//now put missing values if they have not been asekd this questions
#delimit ;
replace no_sw_comparison=. if LW23_W201=="No" & LW23_W202=="No" & LW23_W203=="No" & 
	LW23_W204=="No" & LW23_W205=="No" & LW23_W206=="No" & LW23_W207=="No" & 
	LW23_W208=="No" & LW23_W209=="No"
;
#delimit cr
tab no_sw_comparison


gen no_sw_effort=.
replace no_sw_effort=0 if LW23_W205=="No"
replace no_sw_effort=1 if LW23_W205=="Yes"
label var no_sw_effort "Haven't switched supplier bec switching involves too much effort"
label define no_sw_effortl 0 "Not true" 1 "True"
label value no_sw_effort no_sw_effortl
*check 
tab LW23_W205
tab no_sw_effort


//now put missing values if they have not been asekd this questions
#delimit ;
replace no_sw_effort=. if LW23_W201=="No" & LW23_W202=="No" & LW23_W203=="No" & 
	LW23_W204=="No" & LW23_W205=="No" & LW23_W206=="No" & LW23_W207=="No" & 
	LW23_W208=="No" & LW23_W209=="No"
;
#delimit cr
tab no_sw_effort


gen no_sw_feelgood=.
replace no_sw_feelgood=0 if LW23_W206=="No"
replace no_sw_feelgood=1 if LW23_W206=="Yes"
label var no_sw_feelgood "Haven't switched supplier bec feel well with current supplier"
label define no_sw_feelgoodl 0 "Not true" 1 "True"
label value no_sw_feelgood no_sw_feelgoodl
*check
tab LW23_W206
tab no_sw_feelgood


//now put missing values if they have not been asekd this questions
#delimit ;
replace no_sw_feelgood=. if LW23_W201=="No" & LW23_W202=="No" & LW23_W203=="No" & 
	LW23_W204=="No" & LW23_W205=="No" & LW23_W206=="No" & LW23_W207=="No" & 
	LW23_W208=="No" & LW23_W209=="No"
;
#delimit cr
tab no_sw_feelgood


gen no_sw_interest=.
replace no_sw_interest=0 if LW23_W207=="No"
replace no_sw_interest=1 if LW23_W207=="Yes"
label var no_sw_interest "Haven't switched supplier bec not interested in a switch"
label define no_sw_interestl 0 "Not true" 1 "True"
label value no_sw_interest no_sw_interestl
*check
tab LW23_W207
tab no_sw_interest


//now put missing values if they have not been asekd this questions
#delimit ;
replace no_sw_interest=. if LW23_W201=="No" & LW23_W202=="No" & LW23_W203=="No" & 
	LW23_W204=="No" & LW23_W205=="No" & LW23_W206=="No" & LW23_W207=="No" & 
	LW23_W208=="No" & LW23_W209=="No"
;
#delimit cr
tab no_sw_interest


gen no_sw_wrong=.
replace no_sw_wrong=0 if LW23_W208=="No"
replace no_sw_wrong=1 if LW23_W208=="Yes"
label var no_sw_wrong "Haven't switched supplier bec too many things could go wrong"
label define no_sw_wrongl 0 "Not true" 1 "True"
label value no_sw_wrong no_sw_wrongl
*check
tab LW23_W208
tab no_sw_wrong


//now put missing values if they have not been asekd this questions
#delimit ;
replace no_sw_wrong=. if LW23_W201=="No" & LW23_W202=="No" & LW23_W203=="No" & 
	LW23_W204=="No" & LW23_W205=="No" & LW23_W206=="No" & LW23_W207=="No" & 
	LW23_W208=="No" & LW23_W209=="No"
;
#delimit cr
tab no_sw_wrong


gen no_sw_none=.
replace no_sw_none=0 if LW23_W209=="No"
replace no_sw_none=1 if LW23_W209=="Yes"  
label var no_sw_none "Haven't switched supplier bec nothing of the above mentioned"
label define no_sw_nonel 0 "Not true" 1 "True"
label value no_sw_none no_sw_nonel
*check
tab LW23_W209
tab no_sw_none


//now put missing values if they have not been asekd this questions
#delimit ;
replace no_sw_none=. if LW23_W201=="No" & LW23_W202=="No" & LW23_W203=="No" & 
	LW23_W204=="No" & LW23_W205=="No" & LW23_W206=="No" & LW23_W207=="No" & 
	LW23_W208=="No" & LW23_W209=="No"
;
#delimit cr
tab no_sw_none


//NOTE: In 2009 this is a merge between EI5 where exact number was given
//		and EI5b where a range was given

gen consumption=.
replace consumption=1 if EI5B=="900 kWh"
replace consumption=2 if EI5B=="900 - 2.350 kWh"
replace consumption=3 if EI5B=="2.350 - 5.500 kWh"
replace consumption=4 if EI5B=="5.500 - 13.750 kWh"
replace consumption=5 if EI5B=="13.750 kWh"
replace consumption=6 if EI5B=="Weet niet"
label var consumption "yearly electricity consumption (past year)"
#delimit;
label define consumptionl 1 "<900kWh" 2 "900-2350 kWh" 3 "2350-5500 kWh" 4 "5500-13750 kWh"
	5 ">13750 kWh" 6 "don't know"
;
#delimit cr
label values consumption consumptionl
*check 
tab EI5B
tab consumption 

//Now, add those that gave a specific number in EI5
replace EI5=. if EI5==999999

gen helpcons=.
replace helpcons=1 if EI5<900
replace helpcons=2 if EI5>=900 & EI5<2350
replace helpcons=3 if EI5>=2350 & EI5<5500
replace helpcons=4 if EI5>=5500 & EI5<13750
replace helpcons=5 if EI5>=13750 
*replace helpcons=6 if EI5==99999 //I do not know what this means
replace helpcons=. if EI5==.
tab helpcons

//add
count if consumption==. 
replace consumption=helpcons if consumption==.
tab consumption

gen energycost=.
label var energycost "How important are energy costs within total HH costs"
replace energycost=1 if EI7=="Helemaal niet belangrijk"
replace energycost=2 if EI7=="Niet echt zo belangrijk"
replace energycost=3 if EI7=="Nogal belangrijk"
replace energycost=4 if EI7=="Zeer belangrijk"
replace energycost=5 if EI7=="Geen mening"
label define energycostl 1 "not important at all" 2 "rather not important" 3 "rather important" 4 "very important" 5 "no opinion"
label values energycost energycostl
*check
tab energycost

gen aware_vreg=.
replace aware_vreg=1 if IV3=="Ja, ik weet globaal wat de VREG doet"
replace aware_vreg=2 if IV3=="Ja, ik weet goed wat de VREG doet"
replace aware_vreg=3 if IV3=="Ja, maar ik ken de VREG alleen van naam"
replace aware_vreg=4 if IV3=="Neen"
label var aware_vreg "do you know VREG (2012-13 only 50%)"
label define aware_vregl 1 "yes, I know well" 2 "yes, I know"	3 "yes, but only by name" 4 "no"
label value aware_vreg aware_vregl
*check
tab aware_vreg

gen aware_vtest=.
replace aware_vtest=1 if IV8=="Ja"
replace aware_vtest=2 if IV8=="Neen"
label var aware_vtest "do you know v-test (only if knew VREG (in 2012-13 only 50%))"
label define aware_vtestl 1 "yes" 2 "no"
label value aware_vtest aware_vtestl
*check
tab aware_vtest
tab IV8

gen done_vtest=.
replace done_vtest=1 if IV9_W2=="Ja"
replace done_vtest=2 if IV9_W2=="Neen"
label var done_vtest "have you done v-test (only if knew VREG (in 2012-13 only 50%) and others)"
label define done_vtestl 1 "yes" 2 "no"
label value done_vtest done_vtestl
*check
tab done_vtest
tab IV9_W2

gen contacted=.
replace contacted=1 if LW2_W2=="Ja"
replace contacted=2 if LW2_W2=="Neen"
replace contacted=3 if LW2_W2=="Weet niet"
label var contacted "Have you been contacted by supplier in last 12 months"
label define contactedl 1 "yes" 2 "no" 3 "don't know"
label values contacted contactedl
*check
tab contacted


/*	In 2009 it is 
		- "will you AT MATURITY of your contract"
		- A the contract extend (certaintly vs likely)"
		   or
		  B "switch to another supplier (certainly vs likely)"
-> coded as: do you consider switching
	therefore answers A become
		certainly extend ==> not at all
		likely extend ==> probably not
*/
gen sw_intention=.
replace sw_intention=1 if LW15=="Het contract zeker verlengen"
replace sw_intention=2 if LW15=="Het contract waarschijnlijk verlengen"
replace sw_intention=3 if LW15=="Waarschijnlijk overstappen naar een andere leverancier"
replace sw_intention=4 if LW15=="Zeker overstappen naar een andere leverancier"
replace sw_intention=5 if LW15=="Ik weet het (nog) niet"
label var sw_intention "Do you consider switching in the next 6 months (11-14) / at maturity (08-10)"
label define sw_intentionl 1 "not at all" 2 "probably not" 3 "probably" 4 "certainly" 5 "don't know (yet)"
label value sw_intention sw_intentionl
*check
tab LW15
tab sw_intention

gen sw_intention_default=.
replace sw_intention_default=1 if LW241=="Zeker en vast niet"
replace sw_intention_default=2 if LW241=="Waarschijnlijk niet"
replace sw_intention_default=3 if LW241=="Waarschijnlijk wel"
replace sw_intention_default=4 if LW241=="Zeker en vast wel"
replace sw_intention_default=5 if LW241=="Weet niet"
replace sw_intention_default=5 if sw_intention_default==9
label var sw_intention_default  "Do you consider switching in the next 6 months (11-14) / at maturity (08-10)(only if default)"
label define sw_intention_defaultl 1 "not at all" 2 "probably not" 3 "probably" 4 "certainly" 5 "don't know"
label value sw_intention_default sw_intention_defaultl
*check
tab LW241
tab sw_intention_default

gen green_contract=.
replace green_contract=1 if ME2_W2=="Ja"
replace green_contract=2 if ME2_W2=="Neen"
replace green_contract=3 if ME2_W2=="Weet niet"
label var green_contract "current contract is green (only 50% asked)"
label define green_contractl 1 "yes" 2 "no" 3 "don't know"
label values green_contract green_contractl
*check
tab green_contract
tab green_contract contract
tab contract



/* two modalities were not asked: 
- sw_solar
- sw_nuclear */

gen sw_cheaper=.
replace sw_cheaper=1 if L11W2_1=="ja"
replace sw_cheaper=2 if L11W2_1=="nee"
label var sw_cheaper "supplier chosen because cheaper (only if elec contract was signed)"
label define sw_cheaperl  1 "yes" 2 "no" 3 "don't know"
label values sw_cheaper sw_cheaperl
*check
tab sw_cheaper
tab L11W2_1

gen sw_service=.
replace sw_service=1 if L11W2_2=="ja"
replace sw_service=2 if L11W2_2=="nee"
label var sw_service "Have chosen supplier because better service (only if elec contract was signed)"
label define sw_servicel 1 "yes" 2 "no" 3 "don't know"	
label values sw_service sw_servicel
*check
tab sw_service
tab L11W2_2

gen sw_reliable=.
replace sw_reliable=1 if L11W2_3=="ja"
replace sw_reliable=2 if L11W2_3=="nee"
label var sw_reliable "Have chosen supplier because reliable (only if elec contract was signed)"
label define sw_reliablel 1 "yes" 2 "no" 3 "don't know"	
label values sw_reliable sw_reliablel
*check
tab sw_reliable
tab L11W2_3

gen sw_family=.
replace sw_family=1 if L11W2_4=="ja"
replace sw_family=2 if L11W2_4=="nee"
label var sw_family "Have chosen supplier because same as family/acquaintances (only if elec contract was signed)"
label define sw_familyl 1 "yes" 2 "no" 3 "don't know"
label values sw_family sw_familyl
*check
tab sw_family
tab L11W2_4

gen sw_green=.
replace sw_green=1 if L11W2_6=="ja"
replace sw_green=2 if L11W2_6=="nee"
label var sw_green "Have chosen supplier because green elec (only if elec contract was signed)"
label define sw_greenl 1 "yes" 2 "no" 3 "don't know"
label values sw_green sw_greenl
*check
tab sw_green
tab L11W2_6

gen sw_additional=.
replace sw_additional=1 if L11W2_7=="ja"
replace sw_additional=2 if L11W2_7=="nee"
label var sw_additional "Have chosen supplier because additional service (only if elec contract was signed)"
label define sw_additionall 1 "yes" 2 "no" 3 "don't know"
label values sw_additional sw_additionall
*check
tab sw_additional
tab L11W2_7


* Create year variable (to facilitate merging of yearly surveys).
gen year=2009

/*In 2009, it seems there is no weighting variable
//Rename weight variable.
rename Gewichtformaatxxxxxx weight
*/

#delimit;
keep //weight 
	id hometype //socialhome 
	ownership income size_hh kids gender education employment
	supplier contract sw_history sw_frequency //same_supplier 
	green_contract //sw_reason_gen same_reason
	sw_cheaper sw_service sw_reliable //sw_solar sw_nuclear 
	sw_family sw_green sw_additional 
	no_sw_possibility //no_sw_how 
	no_sw_cheaper no_sw_comparison no_sw_effort no_sw_feelgood no_sw_interest 
	no_sw_wrong no_sw_none 	//no_sw_dontknow green_confidence green_future 
	//green_reason heating1 heating2 heating3 meter 
	consumption energycost //solar price_change price_percent aware_free info_liberalization 
	aware_vreg aware_vtest done_vtest
	//same_aware 
	sw_intention sw_intention_default 
	//sw_saving sw_saving_nb 
	socialtariff default
	age agecat
	contacted
;
#delimit cr
numlabel , add

* Create a year variable to identify surveys when appending them into one file.
gen year = 2009

*********************************
* Save cleaned 2009 survey as Stata file.
save `"${PATH_OUT_DATA}/surveydata2009_clean"', replace
****************************************************************************
