/*
	Clean the survey data sets and and save as separate Stata-dta-files
	and append into one survey data file.
	This file cleans 2004 survey.
	NOTE THAT THIS FILE IS NOT RELEVANT FOR THIS PROJECT.

*/

clear
capture log close
version 13
set more off
set mem 4g
* Header do-File with path definitions, those end up in global macros.
include project_paths
log using `"${PATH_OUT_DATA}/log/`1'.log"', replace

*********************************
* Load Stata file generated by readin-file.
use `"${PATH_OUT_DATA}/surveydataraw2004.dta"', clear
rename QUESTNUM id

/* The following were not asked in 2004
- socialhome
- kids
*/

gen age=.
replace age=S2A
label var age "age or respondent"
*check
sum age

gen agecat=1 if age<=34
replace agecat=2 if age>24 & age<=34
replace agecat=3 if age>34 & age<=44
replace agecat=4 if age>44 & age<=54
replace agecat=5 if age>54 & age<=64
replace agecat=6 if age>64
label var agecat "age category of respondent"
label define agecatl 1 "18-24" 2 "25-34" 3 "35-44" 4 "45-54" 5 "55-64" 6 "65+"
label values agecat agecatl
*check  
tab agecat

// NOTE in variable 'hometype' we regroup "detached house, townhouse and semi detached house into HOUSE 
//      to be consistent with data collection in the year 2011
gen hometype=.
label var hometype "type of house"
replace hometype=0 if SP4==20
replace hometype=1 if SP4==1 | SP4==2 | SP4==3
replace hometype=2 if SP4==4
label define hometypel 0 "other" 1 "house" 2 "apartment" 
label values hometype hometypel  
*check
tab hometype


gen ownership=.
replace ownership=1 if SP5==1
replace ownership=2 if SP5==2
label var ownership "home ownership"
label define ownershipl 1 "owner" 2 "tenant"
label values ownership ownershipl
*check 
tab SP5
tab ownership

rename S5 size_hh
label var size_hh "size of household"
*check
tab size_hh


gen gender=.
replace gender=1 if S1==1
replace gender=2 if S1==2
label var gender "gender of respondent"
label define genderl 1 "male" 2 "female"
label values gender genderl
*check
tab gender

//the B in the question n� means that I take values of the person with main income
gen education=.
replace education=1 if S9B==1
replace education=2 if S9B==2 | S9B==3 | S9B==4 | S9B==5
replace education=3 if S9B==6
replace education=4 if S9B==7
label var education "highest diploma"
#delimit ;
label define educationl 1 "primary education" 2 "secondary education" 
	3 "higher eudcation (non-uni)" 4 "university" 
;
#delimit cr
label values education educationl
*check
tab S9B
tab education

//the B in the question n� means that I take values of the person with main income
gen employment=.
replace employment=1 if S8B<=14
replace employment=2 if S8B==17
replace employment=3 if S8B==18
replace employment=4 if S8B==15 | S8B ==19
replace employment=5 if S8B==16
label var employment "employment status(more details available)"
#delimit ;
label define employmentl 1 "working" 2 "student" 3 "housewife" 
	4 "unemployed and other inactive" 5 "retired" 6 "don't know"
;
#delimit cr
label values employment employmentl
*check
tab S8B
tab employment
	
*label suppliers.
gen supplier=.
replace supplier=95 if Q2==1 //apparently part of luminus since 2004
replace supplier=10 if Q2==2
replace supplier=12 if Q2==3
replace supplier=9 if Q2==4
replace supplier=25 if Q2==5
replace supplier=27 if Q2==6
replace supplier=98 if Q2==7 | Q2==19 | Q2==18
replace supplier=99 if Q2==20
label var supplier "current electricity supplier"
#delimit ;
label define supplierl 1 "antargaz" 2 "belpower" 6 "eon" 9 "ebem" 10 "ecopower" 
	12 "ecs" 14 "elegant" 	17 "eneco" 20 "essent" 24 "lampiris" 25 "edf-luminus" 
	27 "nuon" 28 "octaplus" 32 "spe-luminus" 34 "wasewind"	35 "wingas"	43 "energie2030"
	45 "eni" 49 "watz" 50 "agem TSO" 51 "eandis TSO" 52 "infrax TSO" 53 "pbe TSO"
	54 "social supplier" 95 "citypower" 96 "interelecta" 97 "iverlek" 98 "other" 
	99 "don't know"
;
#delimit cr
label values supplier supplierl
*check 
tab supplier

gen contract=.
destring Q25 Q26 Q27, replace
replace contract=2 if Q25==1 | Q26==1 | Q27==1 
//1735 changes
replace contract=1 if Q26==2 | Q26==4 | Q26==5 | Q27==2 | Q27==3 | Q27==4 | Q27==5
//296 changes
label var contract "have you signed a contract? (in 2011-13 only asked if potentially on a default)"
label define contractl 1 "yes (i.e. on a competitive trariff)" 2 "no (i.e. on default or social tariff)" 3 "don't know"
label values contract contractl
*check
tab contract
tab supplier contract


gen socialtariff=.
replace socialtariff=2 
replace socialtariff=1 if supplier==50 | supplier==51 | supplier==52 | supplier==53 | supplier==54 | supplier==97 
label var socialtariff "on a social tariff (not an original question)"
label define socialtariffl 1 "yes" 2 "no"
label values socialtariff socialtariffl
*check
tab socialtariff
//


gen default=.
destring Q25 Q26 Q27, replace
replace default=2 if Q26==2 | Q26==4 | Q26==5 | Q27==2 | Q27==3 | Q27==4 | Q27==5
replace default=1 if Q25==1 | Q26==1 | Q27==1 
label var default "on a default tariff (not an original question)"
label define defaultl 1 "yes" 2 "no" 3 "don't know"
label values default defaultl
*check
tab default
tab supplier default


rename Q10 energycost
label var energycost "How important are energy costs within total HH costs"
gen energycost_help=energycost*100
drop energycost
gen energycost=.
label var energycost "How important are energy costs within total HH costs"
replace energycost=1 if energycost_help==400
replace energycost=2 if energycost_help==300
replace energycost=3 if energycost_help==200
replace energycost=4 if energycost_help==100
replace energycost=5 if energycost_help==500
label define energycostl 1 "not important at all" 2 "rather not important" 3 "rather important" 4 "very important" 5 "no opinion"
label values energycost energycostl
*check
tab energycost

gen no_sw_possibility=.
replace no_sw_possibility=1 if Q35_1=="4" | Q35_1=="5"
replace no_sw_possibility=0 if Q35_1=="2" | Q35_1=="3" | Q35_1=="1"
label var no_sw_possibility "Haven't switched supplier bec didn't know that I can switch"
label define no_sw_possibilityl 0 "Not true" 1 "True"
label values no_sw_possibility no_sw_possibilityl
*check
tab Q35_1
tab no_sw_possibility

gen no_sw_cheaper=.
replace no_sw_cheaper=1 if Q35_2=="4" | Q35_2=="5"
replace no_sw_cheaper=0 if Q35_2=="2" | Q35_2=="3" | Q35_2=="1"
label var no_sw_cheaper "Haven't switched supplier bec didn't receive a better offer"
label define no_sw_cheaperl 0 "Not true" 1 "True"
label values no_sw_cheaper no_sw_cheaperl
*check
tab Q35_2	
tab no_sw_cheaper	

gen no_sw_comparison=.
replace no_sw_comparison=1 if Q35_3=="4" | Q35_3=="5"
replace no_sw_comparison=0 if Q35_3=="2" | Q35_3=="3" | Q35_3=="1"
label var no_sw_comparison "Haven't switched supplier bec difficult to compare suppliers"
label define no_sw_comparisonl 0 "Not true" 1 "True"
label values no_sw_comparison no_sw_comparisonl
*check
tab Q35_3
tab no_sw_comparison

gen no_sw_feelgood=.
replace no_sw_feelgood=1 if Q35_4=="4" | Q35_4=="5"
replace no_sw_feelgood=0 if Q35_4=="2" | Q35_4=="3" | Q35_4=="1"
label var no_sw_feelgood "Haven't switched supplier bec feel well with current supplier"
label define no_sw_feelgoodl 0 "Not true" 1 "True"
label values no_sw_feelgood no_sw_feelgoodl
*check
tab Q35_4
tab no_sw_feelgood

//this was only asked in 2004
gen no_sw_offer=.
replace no_sw_offer=1 if Q35_5=="4" | Q35_5=="5"
replace no_sw_offer=0 if Q35_5=="2" | Q35_5=="3" | Q35_5=="1"
label var no_sw_offer "Haven't switched supplier bec did not get another offer"
label define no_sw_offerl 0 "Not true" 1 "True"
label values no_sw_offer no_sw_offerl
*check
tab Q35_5
tab no_sw_offer	

gen no_sw_wrong=.
replace no_sw_wrong=1 if Q35_6=="4" | Q35_6=="5"
replace no_sw_wrong=0 if Q35_6=="2" | Q35_6=="3" | Q35_6=="1"
label var no_sw_wrong "Haven't switched supplier bec too many things could go wrong"
label define no_sw_wrongl 0 "Not true" 1 "True"
label values no_sw_wrong no_sw_wrongl
*check
tab Q35_6
tab no_sw_wrong

/* three modalities were not asked: 
- sw_solar
- sw_nuclear
- sw_additional*/

gen sw_cheaper=.
destring Q28_1, replace
replace sw_cheaper=1 if Q28_1==4 | Q28_1==5
replace sw_cheaper=2 if Q28_1==2 | Q28_1==3
replace sw_cheaper=3 if Q28_1==1
label var sw_cheaper "supplier chosen because cheaper (only if elec contract was signed)"
label define sw_cheaperl  1 "yes" 2 "no" 3 "don't know"
label values sw_cheaper sw_cheaperl
*check
tab sw_cheaper
tab Q28_1

gen sw_service=.
destring Q28_2, replace
replace sw_service=1 if Q28_2==4 | Q28_2==5
replace sw_service=2 if Q28_2==2 | Q28_2==3
replace sw_service=3 if Q28_2==1
label var sw_service "Have chosen supplier because better service (only if elec contract was signed)"
label define sw_servicel 1 "yes" 2 "no" 3 "don't know"	
label values sw_service sw_servicel
*check
tab sw_service
tab Q28_2

gen sw_reliable=.
destring Q28_3, replace
replace sw_reliable=1 if Q28_3==4 | Q28_3==5
replace sw_reliable=2 if Q28_3==2 | Q28_3==3
replace sw_reliable=3 if Q28_3==1
label var sw_reliable "Have chosen supplier because reliable (only if elec contract was signed)"
label define sw_reliablel 1 "yes" 2 "no" 3 "don't know"	
label values sw_reliable sw_reliablel
*check
tab sw_reliable
tab Q28_3

gen sw_family=.
destring Q28_4, replace
replace sw_family=1 if Q28_4==4 | Q28_4==5
replace sw_family=2 if Q28_4==2 | Q28_4==3
replace sw_family=3 if Q28_4==1
label var sw_family "Have chosen supplier because same as family/acquaintances (only if elec contract was signed)"
label define sw_familyl 1 "yes" 2 "no" 3 "don't know"
label values sw_family sw_familyl
*check
tab sw_family
tab Q28_4

gen sw_green=.
destring Q28_8, replace
replace sw_green=1 if Q28_8==4 | Q28_8==5
replace sw_green=2 if Q28_8==2 | Q28_8==3
replace sw_green=3 if Q28_8==1
label var sw_green "Have chosen supplier because green elec (only if elec contract was signed)"
label define sw_greenl 1 "yes" 2 "no" 3 "don't know"
label values sw_green sw_greenl
*check
tab sw_green
tab Q28_8

* Create year variable (to facilitate merging of yearly surveys).
gen year=2004
* Rename weight variable.
rename PONDE2 weight

***different from 2013 because no_sw_energy8 no_sw_elec7
#delimit;
keep weight id hometype //socialhome 
	ownership //income 
	size_hh //kids 
	gender education employment	supplier contract //sw_history sw_frequency same_supplier 
	//green_contract sw_reason_gen same_reason 
	sw_cheaper sw_service sw_reliable //sw_solar sw_nuclear 
	sw_family sw_green //sw_additional 
	no_sw_possibility //no_sw_how 
	no_sw_cheaper no_sw_comparison //no_sw_effort 
	no_sw_feelgood //no_sw_interest 
	no_sw_offer no_sw_wrong 
	//no_sw_none 	no_sw_dontknow green_confidence green_future green_reason heating1 heating2 heating3 
	//meter consumption solar price_change price_percent aware_free info_liberalization 
	//aware_vreg aware_vtest same_aware sw_intention sw_intention_default sw_saving 
	//sw_saving_nb 
	socialtariff default
	age agecat
;
#delimit cr
numlabel , add

* Create a year variable to identify surveys when appending them into one file.
gen year = 2004
*********************************
* Save cleaned 2004 survey as Stata file.
save `"${PATH_OUT_DATA}/surveydata2004_clean"', replace
****************************************************************************
