/*
	Clean the survey data sets and and save as separate Stata-dta-files
	and append into one survey data file.
	This file cleans 2008 survey.
NOTE THAT THIS FILE IS NOT RELEVANT FOR THIS PROJECT.
*/

clear
capture log close
version 13
set more off
set mem 4g
* Header do-File with path definitions, those end up in global macros.
include project_paths
log using `"${PATH_OUT_DATA}/log/`1'.log"', replace

*********************************
* Load Stata file generated by readin-file.
use `"${PATH_OUT_DATA}/surveydataraw2008.dta"', clear

rename INTNR id


* Rename 2008 variables

/*not asked in 2008
- socialhome
*/

gen age=.
replace age=P4
label var age "age or respondent"
*check
sum age

gen agecat=1 if age<=24
replace agecat=2 if age>24 & age<=34
replace agecat=3 if age>34 & age<=44
replace agecat=4 if age>44 & age<=54
replace agecat=5 if age>54 & age<=64
replace agecat=6 if age>64
label var agecat "age category of respondent"
label define agecatl 1 "18-24" 2 "25-34" 3 "35-44" 4 "45-54" 5 "55-64" 6 "65+"
label values agecat agecatl
*check  
tab agecat

// NOTE in variable 'hometype' we regroup "detached house, townhouse and semi detached house into HOUSE 
//      to be consistent with data collection in the year 2011
// NOTE add 0 because of year 2004
gen hometype=.
replace hometype=1 if P8==1 | P8==3
replace hometype=2 if P8==2 | P8==4
label var hometype "type of house"
label define hometypel 0 "other" 1 "house" 2 "apartment" 
label values hometype hometypel  
*check
tab hometype



gen ownership=.
replace ownership=1 if P8==1 | P8==2
replace ownership=2 if P8==3 | P8==4
label var ownership "home ownership"
label define ownershipl 1 "owner" 2 "tenant"
label values ownership ownershipl
*check 
tab ownership

rename P11 income
label var income "family net income"
#delimit ;
label define incomel 1 "< EUR 600" 2 "EUR 600-999.99" 3 "EUR 1,000-1,499.99"
	4 "EUR 1,500-1,999.99 " 5 "EUR 2,000-2,499.99" 6 "EUR 2,500-3,749.99"
	7 "EUR 3,750-4,999.99" 8 "EUR  5,000-6,249.99" 9 "> EUR 6,250"
	10 "I prefer not to tell"
;
#delimit cr
label values income incomel
*check
tab income	

rename P2 size_hh
label var size_hh "size of household"
*check
tab size_hh

rename P3 kids
label var kids "number of kids in household <14 years"
*check
tab kids

rename P5 gender
label var gender "gender of respondent"
label define genderl 1 "male" 2 "female"
label values gender genderl
*check
tab gender

gen education=.
replace education=1 if P6==1
replace education=2 if P6==2 | P6==3
replace education=3 if P6==4 | P6==5
replace education=4 if P6==6
#delimit ;
label define educationl 1 "primary education" 2 "secondary education" 
	3 "higher eudcation (non-uni)" 4 "university"
;
#delimit cr
label values education educationl
*check
tab education
tab P6

gen employment=.
replace employment=1 if P7<=2
replace employment=3 if P7==3
replace employment=4 if P7==4
replace employment=5 if P7==5
label var employment "employment status (more details available)"
#delimit ;
label define employmentl 1 "working" 2 "student" 3 "housewife" 
	4 "unemployed and other inactive" 5 "retired" 6 "don't know"
;
#delimit cr
label values employment employmentl
*check
tab P7
tab employment

gen supplier=.
replace supplier=95 if LW6TOT==1
replace supplier=9 if LW6TOT==2
replace supplier=10 if LW6TOT==3
replace supplier=12 if LW6TOT==4
replace supplier=17 if LW6TOT==5
replace supplier=20 if LW6TOT==6
replace supplier=24 if LW6TOT==7
replace supplier=25 if LW6TOT==8
replace supplier=27 if LW6TOT==9
replace supplier=2 if LW6TOT==10
replace supplier=34 if LW6TOT==11
replace supplier=32 if LW6TOT==12
replace supplier=51 if LW6TOT==13
replace supplier=52 if LW6TOT==14
replace supplier=53 if LW6TOT==15
replace supplier=50 if LW6TOT==16
replace supplier=54 if LW6TOT==17
replace supplier=97 if LW6TOT==27
#delimit ;
replace supplier=98 if LW6TOT==98 | LW6TOT==18 | LW6TOT==20 | LW6TOT==21 | LW6TOT==22 | 
	LW6TOT==23 | LW6TOT==24 | LW6TOT==25 | LW6TOT==26 | LW6TOT==28 | LW6TOT==29 | LW6TOT==30
	;
#delimit cr
replace supplier=99 if LW6TOT==99 | LW6TOT==19
label var supplier "current electricity supplier"
#delimit ;
label define supplierl 1 "antargaz" 2 "belpower" 6 "eon" 9 "ebem" 10 "ecopower" 
	12 "ecs" 14 "elegant" 	17 "eneco" 20 "essent" 24 "lampiris" 25 "edf-luminus" 
	27 "nuon" 28 "octaplus" 32 "spe-luminus" 34 "wasewind"	35 "wingas"	43 "energie2030"
	45 "eni" 49 "watz" 50 "agem TSO" 51 "eandis TSO" 52 "infrax TSO" 53 "pbe TSO"
	54 "social supplier" 95 "citypower" 96 "interelecta" 97 "iverlek" 98 "other" 
	99 "don't know"
;
#delimit cr
label values supplier supplierl
*check 
tab LW6TOT
tab supplier

rename LW5 contract
label var contract "have you signed a contract? (in 2011-13 only asked if potentially on a default)"
label define contractl 1 "yes (i.e. on a competitive trariff)" 2 "no (i.e. on default or social tariff)" 3 "don't know"
label values contract contractl
*check
tab contract
tab supplier contract

gen socialtariff=.
replace socialtariff=2 
replace socialtariff=1 if supplier==50 | supplier==51 | supplier==52 | supplier==53 | supplier==54 | supplier==97 
label var socialtariff "on a social tariff with elec (not an original question)"
label define socialtariffl 1 "yes" 2 "no"
label values socialtariff socialtariffl
*check
tab socialtariff

gen default=.
replace default=2
replace default=1 if contract==2
replace default=3 if contract==3
label var default "on a default tariff (not an original question)"
label define defaultl 1 "yes" 2 "no" 3 "don't know"
label values default defaultl
*check
tab default
//1164
tab supplier default

//In 2008, Q: With how many suppliers did you sign a contract
//NOTE: In other years the question was: how often have you switched = 
//		--> one supplier less than coded
rename lw7 sw_frequency
destring sw_frequency, replace
replace sw_frequency=sw_frequency-1
label var sw_frequency "how often have you changed elec supplier"
label define sw_frequencyl 98 "don't know" 
label values sw_frequency sw_frequencyl
*check
tab sw_frequency

//NOTE: In 2008, this is constructed from question 7 
//In >2011 this variable has missing values if person is on default
// ->same here
gen sw_history=. //all those that did not answer sw_frequency are on default
				 // tab contract if sw_frequency==.
replace sw_history=1 if sw_frequency==1 | sw_frequency==2 | sw_frequency==3 | sw_frequency==4
replace sw_history=2 if sw_frequency==0
replace sw_history=3 if sw_frequency==98
label var sw_history "have you ever changed electricity supplier"
label define sw_historyl 1 "yes" 2 "no" 3 "don't know"
label values sw_history sw_historyl
*check
tab sw_history

tab LW23_1
rename LW23_1 no_sw_possibility
label var no_sw_possibility "Haven't switched supplier bec didn't know that I can switch"
label define no_sw_possibilityl 0 "Not true" 1 "True"
label value no_sw_possibility no_sw_possibilityl
*check
tab no_sw_possibility

tab LW23_2
rename LW23_2 no_sw_cheaper
label var no_sw_cheaper "Haven't switched supplier bec didn't receive a better offer"
label define no_sw_cheaperl 0 "Not true" 1 "True"
label value no_sw_cheaper no_sw_cheaperl
*check
tab no_sw_cheaper
tab LW23_3
rename LW23_3 no_sw_comparison
label var no_sw_comparison "Haven't switched supplier bec difficult to compare suppliers"
label define no_sw_comparisonl 0 "Not true" 1 "True"
label value no_sw_comparison no_sw_comparisonl
*check
tab no_sw_comparison

tab LW23_4
rename LW23_4 no_sw_feelgood
label var no_sw_feelgood "Haven't switched supplier bec feel well with current supplier"
label define no_sw_feelgoodl 0 "Not true" 1 "True"
label value no_sw_feelgood no_sw_feelgoodl
*check
tab no_sw_feelgood

tab LW23_5
rename LW23_5 no_sw_interest
label var no_sw_interest "Haven't switched supplier bec not interested in a switch"
label define no_sw_interestl 0 "Not true" 1 "True"
label value no_sw_interest no_sw_interestl
*check
tab no_sw_interest

tab LW23_6
rename LW23_6 no_sw_wrong
label var no_sw_wrong "Haven't switched supplier bec too many things could go wrong"
label define no_sw_wrongl 0 "Not true" 1 "True"
label value no_sw_wrong no_sw_wrongl
*check
tab no_sw_wrong

tab LW23_7
rename LW23_7 no_sw_none
label var no_sw_none "Haven't switched supplier bec nothing of the above mentioned"
label define no_sw_nonel 0 "Not true" 1 "True"
label value no_sw_none no_sw_nonel
*check
tab no_sw_none

//NOTE: In 2008 this is a merge between EI5 where exact number was given
//		and EI5b where a range was given
rename EI5b consumption
label var consumption "yearly electricity consumption (past year)"
#delimit;
label define consumptionl 1 "<900kWh" 2 "900-2350 kWh" 3 "2350-5500 kWh" 4 "5500-13750 kWh"
	5 ">13750 kWh" 6 "don't know"
;
#delimit cr
label values consumption consumptionl
*check 
tab consumption 

//Now, add those that gave a specific number in EI5
replace EI5=. if EI5==999999
gen helpcons=.
replace helpcons=1 if EI5<900
replace helpcons=2 if EI5>=900 & EI5<2350
replace helpcons=3 if EI5>=2350 & EI5<5500
replace helpcons=4 if EI5>=5500 & EI5<13750
replace helpcons=5 if EI5>=13750 
replace helpcons=6 if EI5==99999 //I do not know what this means
replace helpcons=. if EI5==.
tab helpcons

//add
count if consumption==. 
replace consumption=helpcons if consumption==.
tab consumption

rename EI7 energycost
label var energycost "How important are energy costs within total HH costs"
replace energycost=5 if energycost==9
label var energycost "How important are energy costs within total HH costs"
label define energycostl 1 "not important at all" 2 "rather not important" 3 "rather important" 4 "very important" 5 "no opinion"
label values energycost energycostl
*check
tab energycost
gen contact=lw1
label var contact "Were you in contact with another supplier in the last 12 months"
label define contactl 1 "yes" 2 "no" 3 "don't know"
label values contact contactl
*check
tab contact
gen contact_direction= lw2b_1
replace contact_direction=2 if contact_direction==0
label var contact_direction "Have you been contacted by the supplier"
label define contact_directionl 1 "yes" 2 "no" 
label values contact_direction contact_directionl
*check
tab contact_direction

*construct: contacted as in 2009-10
gen contacted=2
replace contacted=1 if contact==1 & contact_direction==1
replace contacted=3 if contact==3 
label var contacted "Have you been contacted by supplier in last 12 months"
label define contactedl 1 "yes" 2 "no" 3 "don't know"
label values contacted contactedl
*check
tab contacted

rename LW15 sw_intention
label var sw_intention "Do you consider switching in the next 6 months (11-14) / at maturity (08-10)"
label define sw_intentionl 1 "not at all" 2 "probably not" 3 "probably" 4 "certainly" 5 "don't know (yet)"
label value sw_intention sw_intentionl
*check
tab sw_intention

rename LW24 sw_intention_default
replace sw_intention_default=5 if sw_intention_default==9
label var sw_intention_default  "Do you consider switching in the next 6 months (11-14) / at maturity (08-10) (only if default)"
label define sw_intention_defaultl 1 "not at all" 2 "probably not" 3 "probably" 4 "certainly" 5 "don't know"
label value sw_intention_default sw_intention_defaultl
*check
tab sw_intention_default
//only those (1) with default supplier (2) who have not signed a contract are asked
rename ME1 green_contract
label var green_contract "current contract is green (only 50% asked)"
label define green_contractl 1 "yes" 2 "no" 3 "don't know"
label values green_contract green_contractl
*check
tab green_contract
tab green_contract contract


/* two modalities were not asked: 
- sw_solar
- sw_nuclear */

gen sw_cheaper=.
replace sw_cheaper=1 if LW11_1==1
replace sw_cheaper=2 if LW11_1==0
label var sw_cheaper "supplier chosen because cheaper (only if elec contract was signed)"
label define sw_cheaperl  1 "yes" 2 "no" 3 "don't know"
label values sw_cheaper sw_cheaperl
*check
tab sw_cheaper
tab LW11_1

gen sw_service=.
replace sw_service=1 if LW11_2==1
replace sw_service=2 if LW11_2==0
label var sw_service "Have chosen supplier because better service (only if elec contract was signed)"
label define sw_servicel 1 "yes" 2 "no" 3 "don't know"	
label values sw_service sw_servicel
*check
tab sw_service
tab LW11_2

gen sw_reliable=.
replace sw_reliable=1 if LW11_3==1
replace sw_reliable=2 if LW11_3==0
label var sw_reliable "Have chosen supplier because reliable (only if elec contract was signed)"
label define sw_reliablel 1 "yes" 2 "no" 3 "don't know"	
label values sw_reliable sw_reliablel
*check
tab sw_reliable
tab LW11_3

gen sw_family=.
replace sw_family=1 if LW11_4==1
replace sw_family=2 if LW11_4==0
label var sw_family "Have chosen supplier because same as family/acquaintances (only if elec contract was signed)"
label define sw_familyl 1 "yes" 2 "no" 3 "don't know"
label values sw_family sw_familyl
*check
tab sw_family
tab LW11_4

gen sw_green=.
replace sw_green=1 if LW11_6==1
replace sw_green=2 if LW11_6==0
label var sw_green "Have chosen supplier because green elec (only if elec contract was signed)"
label define sw_greenl 1 "yes" 2 "no" 3 "don't know"
label values sw_green sw_greenl
*check
tab sw_green
tab LW11_6

gen sw_additional=.
replace sw_additional=1 if LW11_7==1
replace sw_additional=2 if LW11_7==0
label var sw_additional "Have chosen supplier because additional service (only if elec contract was signed)"
label define sw_additionall 1 "yes" 2 "no" 3 "don't know"
label values sw_additional sw_additionall
*check
tab sw_additional
tab LW11_7

* Create year variable (to facilitate merging of yearly surveys).
gen year=2008
//In 2008, it seems there is no weighting variable
/* Rename weight variable.
rename Gewichtformaatxxxxxx weight
*/

#delimit;
keep //weight 
	id hometype //socialhome 
	ownership income size_hh kids gender education employment
	supplier contract sw_history sw_frequency //same_supplier 
	green_contract //sw_reason_gen same_reason 
	sw_cheaper sw_service sw_reliable //sw_solar sw_nuclear 
	sw_family sw_green sw_additional 
	no_sw_possibility //no_sw_how 
	no_sw_cheaper no_sw_comparison //no_sw_effort 
	no_sw_feelgood no_sw_interest no_sw_wrong no_sw_none 
	//no_sw_dontknow green_confidence green_future green_reason heating1 heating2 heating3 
	//meter 
	consumption energycost //solar price_change price_percent aware_free info_liberalization 
	//aware_vreg aware_vtest same_aware 
	sw_intention sw_intention_default 
	//sw_saving sw_saving_nb 
	socialtariff default
	age agecat
	contacted
;
#delimit cr
numlabel , add

* Create a year variable to identify surveys when appending them into one file.
gen year = 2008

*********************************
* Save cleaned 2008 survey as Stata file.
save `"${PATH_OUT_DATA}/surveydata2008_clean"', replace
****************************************************************************
