/*
	Clean the survey data sets and and save as separate Stata-dta-files
	and append into one survey data file.
	This file cleans 2010 survey.
NOTE THAT THIS FILE IS NOT RELEVANT FOR THIS PROJECT.
*/

clear
capture log close
version 13
set more off
set mem 4g
* Header do-File with path definitions, those end up in global macros.
include project_paths
log using `"${PATH_OUT_DATA}/log/`1'.log"', replace

*********************************
* Load Stata file generated by readin-file.
use `"${PATH_OUT_DATA}/surveydataraw2010.dta"', clear

rename INTNR id

/* The following were not asked in 2010
- socialhome
*/

gen age=.
replace age=P4
label var age "age or respondent"
*check
sum age

gen agecat=1 if age<=34
replace agecat=2 if age>24 & age<=34
replace agecat=3 if age>34 & age<=44
replace agecat=4 if age>44 & age<=54
replace agecat=5 if age>54 & age<=64
replace agecat=6 if age>64
label var agecat "age category of respondent"
label define agecatl 1 "18-24" 2 "25-34" 3 "35-44" 4 "45-54" 5 "55-64" 6 "65+"
label values agecat agecatl
*check  
tab agecat

// NOTE add 0 because of year 2004
rename P8A hometype
label var hometype "type of house"
label define hometypel 0 "other" 1 "house" 2 "apartment" 
label values hometype hometypel  
*check
tab hometype


rename P8B ownership
label var ownership "home ownership"
label define ownershipl 1 "owner" 2 "tenant"
label values ownership ownershipl
*check 
tab ownership

rename P11 income
label var income "family net income"
#delimit ;
label define incomel 1 "< EUR 600" 2 "EUR 600-999.99" 3 "EUR 1,000-1,499.99"
	4 "EUR 1,500-1,999.99 " 5 "EUR 2,000-2,499.99" 6 "EUR 2,500-3,749.99"
	7 "EUR 3,750-4,999.99" 8 "EUR  5,000-6,249.99" 9 "> EUR 6,250"
	10 "I prefer not to tell"
;
#delimit cr
label values income incomel
*check
tab income	

rename P2 size_hh
label var size_hh "size of household"
*check
tab size_hh

rename P3 kids
destring kids, replace
label var kids "number of kids in household <14 years"
*check
tab kids

rename P5 gender
label var gender "gender of respondent"
label define genderl 1 "male" 2 "female"
label values gender genderl
*check
tab gender

gen education=.
replace education=1 if P6==1
replace education=2 if P6==2 | P6==3
replace education=3 if P6==4 | P6==5
replace education=4 if P6==6
#delimit ;
label define educationl 1 "primary education" 2 "secondary education" 
	3 "higher eudcation (non-uni)" 4 "university"
;
#delimit cr
label values education educationl
*check
tab education
tab P6

gen employment=.
replace employment=1 if P7<=2
replace employment=3 if P7==3
replace employment=4 if P7==4
replace employment=5 if P7==5
label var employment "employment status (more details available)"
#delimit ;
label define employmentl 1 "working" 2 "student" 3 "housewife" 
	4 "unemployed and other inactive" 5 "retired" 6 "don't know"
;
#delimit cr
label values employment employmentl
*check
tab P7
tab employment

gen supplier=.
replace supplier=2 if LW6==1
replace supplier=9 if LW6==2
replace supplier=10 if LW6==3
replace supplier=12 if LW6==4
replace supplier=20 if LW6==5
replace supplier=24 if LW6==6
replace supplier=25 if LW6==7
replace supplier=27 if LW6==8
replace supplier=32 if LW6==9
replace supplier=51 if LW6==11
replace supplier=52 if LW6==12
replace supplier=53 if LW6==13
replace supplier=54 if LW6==16 // which one it is seems to be given in lw6a_CodesXX
replace supplier=99 if LW6==17
label var supplier "current electricity supplier"
#delimit ;
label define supplierl 1 "antargaz" 2 "belpower" 6 "eon" 9 "ebem" 10 "ecopower" 
	12 "ecs" 14 "elegant" 	17 "eneco" 20 "essent" 24 "lampiris" 25 "edf-luminus" 
	27 "nuon" 28 "octaplus" 32 "spe-luminus" 34 "wasewind"	35 "wingas"	43 "energie2030"
	45 "eni" 49 "watz" 50 "agem TSO" 51 "eandis TSO" 52 "infrax TSO" 53 "pbe TSO"
	54 "social supplier" 95 "citypower" 96 "interelecta" 97 "iverlek" 98 "other" 
	99 "don't know"
;
#delimit cr
label values supplier supplierl
*check 
tab LW6
tab supplier

//In 2010, this question was coded for everybody
rename LW5 contract
label var contract "have you signed a contract? (in 2011-13 only asked if potentially on a default)"
label define contractl 1 "yes (i.e. on a competitive trariff)" 2 "no (i.e. on default or social tariff)" 3 "don't know"
label values contract contractl
*check
tab contract
tab supplier contract
//NOTE: people with "social supplier" were coded as not having signed a contract


gen socialtariff=.
replace socialtariff=2 
replace socialtariff=1 if supplier==50 | supplier==51 | supplier==52 | supplier==53 | supplier==54 | supplier==97 
label var socialtariff "on a social tariff with elec (not an original question)"
label define socialtariffl 1 "yes" 2 "no"
label values socialtariff socialtariffl
*check
tab socialtariff

gen default=.
replace default=2
replace default=1 if contract==2
replace default=3 if contract==3
label var default "on a default tariff (not an original question)"
label define defaultl 1 "yes" 2 "no" 3 "don't know"
label values default defaultl
*check
tab contract
tab default
tab supplier default

//In 2010, Q: How many different suppliers for electricity, you've already had since 
//	the liberalisation on 1 July 2003?
//NOTE: In other years the question was: how often have you switched = 
//		--> one supplier less than coded
rename LW7 sw_frequency
destring sw_frequency, replace
replace sw_frequency=sw_frequency-1
label var sw_frequency "how often have you changed elec supplier"
label define sw_frequencyl 98 "don't know" 
label values sw_frequency sw_frequencyl
*check
tab sw_frequency

//NOTE: In 2010, this is constructed from question 7 
//In >2011 this variable has missing values if person is on default
// ->same here
gen sw_history=. //all those that did not answer sw_frequency are on default
				 // tab contract if sw_frequency==.
replace sw_history=1 if sw_frequency==1 | sw_frequency==2 | sw_frequency==3
replace sw_history=2 if sw_frequency==0
replace sw_history=3 if sw_frequency==98
label var sw_history "have you ever changed electricity supplier"
label define sw_historyl 1 "yes" 2 "no" 3 "don't know"
label values sw_history sw_historyl
*check
tab sw_history
rename LW23_W21 no_sw_possibility
destring no_sw_possibility, replace
label var no_sw_possibility "Haven't switched supplier bec didn't know that I can switch"
label define no_sw_possibilityl 0 "Not true" 1 "True"
label value no_sw_possibility no_sw_possibilityl
*check
tab no_sw_possibility 
tab no_sw_possibility contract 


rename LW23_W22 no_sw_how 
destring no_sw_how, replace
label var no_sw_how "Haven't switched supplier bec didn't know HOW to switch"
label define no_sw_howl 0 "Not true" 1 "True"
label value no_sw_how no_sw_howl
*check
tab no_sw_how
tab no_sw_how contract


rename LW23_W23 no_sw_cheaper 
destring no_sw_cheaper, replace
label var no_sw_cheaper "Haven't switched supplier bec didn't receive a better offer"
label define no_sw_cheaperl 0 "Not true" 1 "True"
label value no_sw_cheaper no_sw_cheaperl
*check
tab no_sw_cheaper
tab no_sw_cheaper contract


rename LW23_W24 no_sw_comparison
destring no_sw_comparison, replace
label var no_sw_comparison "Haven't switched supplier bec difficult to compare suppliers"
label define no_sw_comparisonl 0 "Not true" 1 "True"
label value no_sw_comparison no_sw_comparisonl
*check
tab no_sw_comparison
tab no_sw_comparison contract


rename LW23_W25 no_sw_effort 
destring no_sw_effort, replace
label var no_sw_effort "Haven't switched supplier bec switching involves too much effort"
label define no_sw_effortl 0 "Not true" 1 "True"
label value no_sw_effort no_sw_effortl
*check 
tab no_sw_effort
tab no_sw_effort contract


rename LW23_W26 no_sw_feelgood 
destring no_sw_feelgood, replace
label var no_sw_feelgood "Haven't switched supplier bec feel well with current supplier"
label define no_sw_feelgoodl 0 "Not true" 1 "True"
label value no_sw_feelgood no_sw_feelgoodl
*check
tab no_sw_feelgood
tab no_sw_feelgood contract


rename LW23_W27 no_sw_interest 
destring no_sw_interest, replace
label var no_sw_interest "Haven't switched supplier bec not interested in a switch"
label define no_sw_interestl 0 "Not true" 1 "True"
label value no_sw_interest no_sw_interestl
*check
tab no_sw_interest
tab no_sw_interest contract


rename LW23_W28 no_sw_wrong
destring no_sw_wrong, replace
label var no_sw_wrong "Haven't switched supplier bec too many things could go wrong"
label define no_sw_wrongl 0 "Not true" 1 "True"
label value no_sw_wrong no_sw_wrongl
*check
tab no_sw_wrong
tab no_sw_wrong contract


rename LW23_W29 no_sw_none 
destring no_sw_none, replace
label var no_sw_none "Haven't switched supplier bec nothing of the above mentioned"
label define no_sw_nonel 0 "Not true" 1 "True"
label value no_sw_none no_sw_nonel
*check
tab no_sw_none
tab no_sw_none contract


//NOTE: In 2010 this is a merge between EI5 where exact number was given
//		and EI5b where a range was given

rename EI5B consumption
destring consumption, replace
label var consumption "yearly electricity consumption (past year)"
#delimit;
label define consumptionl 1 "<900kWh" 2 "900-2350 kWh" 3 "2350-5500 kWh" 4 "5500-13750 kWh"
	5 ">13750 kWh" 6 "don't know"
;
#delimit cr
label values consumption consumptionl
*check 
tab consumption 

//Now, add those that gave a specific number in EI5
replace EI5=. if EI5==999999

gen helpcons=.
replace helpcons=1 if EI5<900
replace helpcons=2 if EI5>=900 & EI5<2350
replace helpcons=3 if EI5>=2350 & EI5<5500
replace helpcons=4 if EI5>=5500 & EI5<13750
replace helpcons=5 if EI5>=13750 
replace helpcons=. if EI5==.
tab helpcons

//add
count if consumption==. 
replace consumption=helpcons if consumption==.

tab consumption

rename EI7 energycost
label var energycost "How important are energy costs within total HH costs"
gen energycost_help=energycost*100
drop energycost
gen energycost=.
label var energycost "How important are energy costs within total HH costs"
replace energycost=1 if energycost_help==400
replace energycost=2 if energycost_help==300
replace energycost=3 if energycost_help==200
replace energycost=4 if energycost_help==100
replace energycost=5 if energycost_help==500
label define energycostl 1 "not important at all" 2 "rather not important" 3 "rather important" 4 "very important" 5 "no opinion"
label values energycost energycostl
*check
tab energycost

rename IV3 aware_vreg
label var aware_vreg "do you know VREG (2012-13 only 50%)"
label define aware_vregl 1 "yes, I know well" 2 "yes, I know"	3 "yes, but only by name" 4 "no"
label value aware_vreg aware_vregl
*check
tab aware_vreg

rename IV8 aware_vtest
destring aware_vtest, replace
label var aware_vtest "do you know v-test (only if knew VREG (in 2012-13 only 50%))"
label define aware_vtestl 1 "yes" 2 "no"
label value aware_vtest aware_vtestl
*check
tab aware_vtest
//NOTE: This was asked only to those that indicated to 
//		- know vreg (all were asked)
//		- have visited the website (only those that new vreg were asked this Q)
//		  This was not a condition in 2012 and 2013.
//NOTE: in 2014 everyone was asked this question

gen done_vtest=IV9_W2
destring done_vtest, replace
label var done_vtest "have you done v-test (only if knew VREG (in 2012-13 only 50%) and others)"
label define done_vtestl 1 "yes" 2 "no"
label value done_vtest done_vtestl
*check
tab done_vtest
tab IV9_W2
//NOTE: Only those that indicated to be aware of v-test were asked 
//		(which could only be answered by those that were asked whether to know VREG
//		=all in 2009, 2010 and 2011)

gen contacted=LW2_W2
label var contacted "Have you been contacted by supplier in last 12 months"
label define contactedl 1 "yes" 2 "no" 3 "don't know"
label values contacted contactedl
*check
tab contacted
tab LW2_W2

rename LW15 sw_intention
destring sw_intention, replace
label var sw_intention "Do you consider switching in the next 6 months (11-14) / at maturity (08-10)"
label define sw_intentionl 1 "not at all" 2 "probably not" 3 "probably" 4 "certainly" 5 "don't know (yet)"
label value sw_intention sw_intentionl
*check
tab sw_intention

rename LW241 sw_intention_default
destring sw_intention_default, replace
replace sw_intention_default=5 if sw_intention_default==9
label var sw_intention_default  "Do you consider switching in the next 6 months (11-14) / at maturity (08-10) (only if default)"
label define sw_intention_defaultl 1 "not at all" 2 "probably not" 3 "probably" 4 "certainly" 5 "don't know"
label value sw_intention_default sw_intention_defaultl
*check
tab sw_intention_default
//only those (1) with default supplier (2) who have not signed a contract are asked

rename ME2_W2 green_contract
destring green_contract, replace
label var green_contract "current contract is green (only 50% asked)"
label define green_contractl 1 "yes" 2 "no" 3 "don't know"
label values green_contract green_contractl
*check
tab green_contract
tab green_contract contract

/* two modalities were not asked: 
- sw_solar
- sw_nuclear */

gen sw_cheaper=.
destring L11W2_1, replace
replace sw_cheaper=1 if L11W2_1==1
replace sw_cheaper=2 if L11W2_1==2
label var sw_cheaper "supplier chosen because cheaper (only if elec contract was signed)"
label define sw_cheaperl  1 "yes" 2 "no" 3 "don't know"
label values sw_cheaper sw_cheaperl
*check
tab sw_cheaper
tab L11W2_1

gen sw_service=.
destring L11W2_2, replace
replace sw_service=1 if L11W2_2==1
replace sw_service=2 if L11W2_2==2
label var sw_service "Have chosen supplier because better service (only if elec contract was signed)"
label define sw_servicel 1 "yes" 2 "no" 3 "don't know"	
label values sw_service sw_servicel
*check
tab sw_service
tab L11W2_2

gen sw_reliable=.
destring L11W2_3, replace
replace sw_reliable=1 if L11W2_3==1
replace sw_reliable=2 if L11W2_3==2
label var sw_reliable "Have chosen supplier because reliable (only if elec contract was signed)"
label define sw_reliablel 1 "yes" 2 "no" 3 "don't know"	
label values sw_reliable sw_reliablel
*check
tab sw_reliable
tab L11W2_3

gen sw_family=.
destring L11W2_4, replace
replace sw_family=1 if L11W2_4==1
replace sw_family=2 if L11W2_4==2
label var sw_family "Have chosen supplier because same as family/acquaintances (only if elec contract was signed)"
label define sw_familyl 1 "yes" 2 "no" 3 "don't know"
label values sw_family sw_familyl
*check
tab sw_family
tab L11W2_4

gen sw_green=.
destring L11W2_6, replace
replace sw_green=1 if L11W2_6==1
replace sw_green=2 if L11W2_6==2
label var sw_green "Have chosen supplier because green elec (only if elec contract was signed)"
label define sw_greenl 1 "yes" 2 "no" 3 "don't know"
label values sw_green sw_greenl
*check
tab sw_green
tab L11W2_6


gen sw_additional=.
destring L11W2_7, replace
replace sw_additional=1 if L11W2_7==1
replace sw_additional=2 if L11W2_7==2
label var sw_additional "Have chosen supplier because additional service (only if elec contract was signed)"
label define sw_additionall 1 "yes" 2 "no" 3 "don't know"
label values sw_additional sw_additionall
*check
tab sw_additional
tab L11W2_7

* Create year variable (to facilitate merging of yearly surveys).
gen year=2010

//In 2010, it seems there is no weighting variable
/* Rename weight variable.
rename Gewichtformaatxxxxxx weight
*/

#delimit;
keep //weight 
	id hometype //socialhome 
	ownership income size_hh kids gender education employment
	supplier contract sw_history sw_frequency //same_supplier 
	green_contract //sw_reason_gen same_reason
	sw_cheaper sw_service sw_reliable //sw_solar sw_nuclear 
	sw_family sw_green sw_additional 
	no_sw_possibility no_sw_how no_sw_cheaper no_sw_comparison no_sw_effort 
	no_sw_feelgood no_sw_interest no_sw_wrong no_sw_none 
	//no_sw_dontknow green_confidence green_future green_reason heating1 heating2 heating3 
	//meter 
	consumption energycost //solar price_change price_percent aware_free info_liberalization 
	aware_vreg aware_vtest done_vtest //same_aware 
	sw_intention sw_intention_default 
	//sw_saving sw_saving_nb 
	socialtariff default
	age agecat
	contacted
; 
#delimit cr
numlabel , add

* Create a year variable to identify surveys when appending them into one file.
gen year = 2010

*********************************
* Save cleaned 2010 survey as Stata file.
save `"${PATH_OUT_DATA}/surveydata2010_clean"', replace
****************************************************************************
